<a href="https://colab.research.google.com/github/MuhammadJahanzaibTariq/ML/blob/main/DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [ ]:
import numpy as np

# for data manipulation, analysis and reading our dataset
import pandas as pd

# for plotting and visualising the data
import matplotlib.pyplot as plt

# Importing the dataset

In [ ]:
dataset = pd.read_csv('Data.csv')
X=dataset.iloc[:,:-1].values # X IS A MATRIX
y=dataset.iloc[:,-1].values #y IS a vector
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Dataset Contains Feature and** dependent_variable vector**
Feature**:Feature are independent variable with which you can predict a dependent variable**

In Our case Country AGE and Salary in Feature or Independent Variable
and Purchased is dependent varibale

**WHAT IS OUR GOAL?:**
      A company want to find that a future customer will purchase the product or not if age Salary and country is given




# Taking Care Of Missing data

This article covers 7 ways to handle missing values in the dataset:
<br>Deleting Rows with missing values<br>
<br>Impute missing values for continuous variable<br>
<br>Impute missing values for categorical variable<br>
<br>Other Imputation Methods<br>
<br>Using Algorithms that support missing values<br>
<br>Prediction of missing values<br>
<br>Imputation using Deep Learning Library — Datawig<br>

https://towardsdatascience.com/7-ways-to-handle-missing-values-in-machine-learning-1a6326adf79e

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])
print(X)



[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding catagorical data

<br>**Encoding catagorical data**<br>
Three type of Encoding(there are more but for now just these three)
<br>1)**Nominal Encoding**<br>
2)**Ordinal Encoding**



<br>1)**Nominal Encoding**:<br>
Nominal Encoding
When we have a feature where variables are just names and there is no order or rank to this variable's feature.

https://miro.medium.com/max/1400/1*cnmpSdK-6hAQJdTUBFxcnA.png

For example: City of person lives in, Gender of person, Marital Status, etc…
In the above example, We do not have any order or rank, or sequence. All the variables in the respective feature are equal. We can't give them any orders or ranks. Those features are called Nominal features.
  -><br>**Nominal Encoding** is further divided into<br>
           ----->    1)**One_Hot Encoding**<br>
           ----->    2)**One_Hot Encoding with many catagorical**<br>
           ----->    3)**Mean Encoding**

2)**Ordinal Encoding**

 When we have a feature where variables have some order/rank.

 https://miro.medium.com/max/654/1*NUzgzszTdpLPZpeKPPf0kQ.png

For example: Student’s performance, Customer’s review, Education of person, etc…

**One_Hot Encoding**

   In one hot encoding you can just see Nominal encoding

   but the thing i am going to discuss is** dummy varible ** trap 

   suppose we have date like this

  Germnay= 100
  France=010
  Spain=001

<table>
  <tr>
    <th>Germany</th>
    <th>France</th>
    <th>Spain</th>
  </tr>
  <tr>
    <td>1</td>
    <td>0</td>
    <td>0</td>
  </tr>
  <tr>
    <td>0</td>
    <td>1</td>
    <td>0</td>
  </tr>
   <tr>
    <td>0</td>
    <td>0</td>
    <td>1</td>
  </tr>
</table>

But we can remove one coloumn this is called dummy varible trap
 Germnay= 10
  France=01
  Spain=00

<table>
  <tr>
    <th>Germany</th>
    <th>France</th>
    <th>Spain</th>
  </tr>
  <tr>
    <td>1</td>
    <td>0</td>
  </tr>
  <tr>
    <td>0</td>
    <td>1</td>
  </tr>
   <tr>
    <td>0</td>
    <td>0</td>
  </tr>
</table>


This will work fine as encoding if we have three make it 3-1=2 nd so on


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Tranning and Test Set

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

https://youtu.be/Y7m9MyPxcyQ<br>
**Q:**what is Feature Scaling?<br>
Ans:Feature Scaling is a technique to standardize the **independent features** present in the data in a fixed range. It is performed during the data pre-processing to handle highly varying magnitudes or values or units<br>
Q why We need Feature Scaling?<br>
Ans:If feature scaling is not done, then a machine learning algorithm tends to weight greater values, higher and consider smaller values as the lower values, regardless of the unit of the values.<br>
**Q:**What are the type of Feature Scaling?<br>

**Min-Max Normalization:** This technique re-scales a feature or observation value with distribution value between 0 and 1.

<center><img src="https://www.geeksforgeeks.org/wp-content/ql-cache/quicklatex.com-282fedefcd0fdf4868ad00ca7e161849_l3.svg" class="ql-img-inline-formula quicklatex-auto-format" alt="X_{\text {new }}=\frac{X_{i}-\min (X)}{\max (x)-\min (X)}" title="Rendered by QuickLaTeX.com" height="42" width="253" style="vertical-align:-14px"></center>

**Standardization:** It is a very effective technique which re-scales a feature value so that it has distribution with 0 mean value and variance equals to 1.

<center><img src="https://www.geeksforgeeks.org/wp-content/ql-cache/quicklatex.com-98d57b82f228c735de66f69c749a14c7_l3.svg" class="ql-img-inline-formula quicklatex-auto-format" alt="X_{\text {new }}=\frac{X_{i}-X_{\text {mean }}}{\text { Standard Deviation }}" title="Rendered by QuickLaTeX.com" height="33" width="293" style="vertical-align:-9px"></center>

Xi=Current value of the **list**
Xmean is also written as μ  MU  As we know Mean is average of all value so Xmean mean Average of all value in List



In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])
print(X_train)
print(X_test)

[[0.0 1.0 0.0 0.2630675731713538 0.1238147854838185]
 [1.0 0.0 0.0 -0.25350147960148617 0.4617563176278856]
 [0.0 0.0 1.0 -1.9753983221776195 -1.5309334063940294]
 [0.0 0.0 1.0 0.05261351463427101 -1.1114197802841526]
 [1.0 0.0 0.0 1.6405850472322605 1.7202971959575162]
 [0.0 0.0 1.0 -0.08131179534387283 -0.16751412153692966]
 [1.0 0.0 0.0 0.9518263102018072 0.9861483502652316]
 [1.0 0.0 0.0 -0.5978808481167128 -0.48214934111933727]]
[[0.0 1.0 0.0 -1.4588292694047795 -0.9016629672292141]
 [0.0 1.0 0.0 1.984964415747487 2.139810822067393]]
